import React from "react";
import AboutUs from "@/components/AboutUs/aboutUs";
import { AboutUsData } from "@/components/AboutUs/aboutUs.mock";
import TeamInfo from "@/components/TeamInfo/teamInfo";
import { TeamInfoData } from "@/components/TeamInfo/teamInfo.mock";

import { ServiceData } from "@/components/ServiceSection/serviceSection.mock";
import ServiceSection from "@/components/ServiceSection/serviceSection";
import ProductList from "../components/ProductList/productList";
import { ProductListData } from "../components/ProductList/productList.mock";
import Head from "next/head";

const about = () => {
  return (
    <>
      <Head>
        <title>Strategy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Image/multiImages/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      <AboutUs {...AboutUsData} />
      <ProductList id={""} url={""} caption={""} {...ProductListData} />
      <TeamInfo {...TeamInfoData} />

      <ServiceSection {...ServiceData} />
    </>
  );
};

export default about;
