import React from "react";
import Products from "@/components/Products/product";
import { ProductsData } from "@/components/Products/product.mock";
import { ContactUsData } from "@/components/ContactUs/contactUs.mock";
import ContactUs from "@/components/ContactUs/contactUs";
import Head from "next/head";

const contact = () => {
  return (
    <>
      <Head>
        <title>Strategy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Image/multiImages/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      <Products {...ProductsData} />
      <ContactUs {...ContactUsData} />
    </>
  );
};

export default contact;
