import React from "react";
import { ServiceData } from "@/components/ServiceSection/serviceSection.mock";
import ServiceSection from "@/components/ServiceSection/serviceSection";
import Products from "@/components/Products/product";
import { ProductsData } from "@/components/Products/product.mock";
import SliderData from "@/components/SliderData/sliderData";
import { SliderInfo } from "@/components/SliderData/sliderData.mock";
import Head from "next/head";

const services = () => {
  return (
    <>
      <Head>
        <title>Strategy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Image/multiImages/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      <ServiceSection {...ServiceData} />
      <Products {...ProductsData} />
      <SliderData {...SliderInfo} />
    </>
  );
};

export default services;
