import React from "react";
import MarketingInfo from "@/components/MarketingInfo/marketingInfo";
import { MarketingData } from "@/components/MarketingInfo/marketingInfo.mock";
import CardList from "@/components/CardList/cardList";
import { CardData } from "@/components/CardList/cardList.mock";
import CategoryList from "@/components/CategoryListing/categoryListing";
import { CategoryListData } from "../components/CategoryListing/categoryListing.mock";
import Head from "next/head";

const work = () => {
  return (
    <>
      <Head>
        <title>Strategy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Image/multiImages/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      <MarketingInfo {...MarketingData} />
      <CardList CardData={CardData} />
      <CategoryList {...CategoryListData} />
    </>
  );
};

export default work;
